export const ENV = {
  SOROBAN_RPC_TESTNET: import.meta.env.VITE_SOROBAN_RPC_TESTNET,
  SOROBAN_RPC_MAINNET: import.meta.env.VITE_SOROBAN_RPC_MAINNET,
  CONTRACT_LOYALTY_ID_TESTNET: import.meta.env.VITE_CONTRACT_LOYALTY_ID_TESTNET,
  CONTRACT_LOYALTY_ID_MAINNET: import.meta.env.VITE_CONTRACT_LOYALTY_ID_MAINNET,
};
